ALTER TABLE tracks ALTER COLUMN name DROP DEFAULT;
ALTER TABLE tracks ALTER COLUMN url DROP DEFAULT;
CREATE OR REPLACE FUNCTION set_updated_at_to_now() RETURNS TRIGGER AS $$BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;$$ language PLPGSQL;
