ALTER TABLE tracks ADD COLUMN name TEXT DEFAULT '' NOT NULL;
ALTER TABLE tracks ADD COLUMN url TEXT DEFAULT '' NOT NULL;
CREATE OR REPLACE FUNCTION set_updated_at_to_now() RETURNS TRIGGER AS $$BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;$$ language PLPGSQL;
